# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
dd_to_dot <- function(dd) {
    .Call(`_Rzdd_dd_to_dot`, dd)
}

#' @export
dd_to_sapporo <- function(dd) {
    .Call(`_Rzdd_dd_to_sapporo`, dd)
}

#' @export
dd_size <- function(dd) {
    .Call(`_Rzdd_dd_size`, dd)
}

#' @export
dd_cardinality <- function(dd) {
    .Call(`_Rzdd_dd_cardinality`, dd)
}

#' zdd_partition
#' 
#' Blah blah blah
#'
#' @param adj_list Adjacency list
#' @export
partition_alg <- function(adj_list, weights, min_w, max_w, n_part, debug = FALSE) {
    .Call(`_Rzdd_partition_alg`, adj_list, weights, min_w, max_w, n_part, debug)
}

