# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dd_to_dot <- function(dd) {
    .Call(`_Rzdd_dd_to_dot`, dd)
}

dd_to_sapporo <- function(dd) {
    .Call(`_Rzdd_dd_to_sapporo`, dd)
}

dd_size <- function(dd) {
    .Call(`_Rzdd_dd_size`, dd)
}

dd_cardinality <- function(dd) {
    .Call(`_Rzdd_dd_cardinality`, dd)
}

dd_solutions <- function(dd, use_obi = TRUE) {
    .Call(`_Rzdd_dd_solutions`, dd, use_obi)
}

enum_part_alg <- function(adj, n_part = 2L, lookahead = TRUE, noloop = FALSE, verbose = TRUE, use_openmp = TRUE) {
    .Call(`_Rzdd_enum_part_alg`, adj, n_part, lookahead, noloop, verbose, use_openmp)
}

min_max_constrain <- function(zdd, weights, lower, upper) {
    .Call(`_Rzdd_min_max_constrain`, zdd, weights, lower, upper)
}

ratio_constrain <- function(zdd, weights, ratio) {
    .Call(`_Rzdd_ratio_constrain`, zdd, weights, ratio)
}

compute_frontier <- function(adj_list) {
    .Call(`_Rzdd_compute_frontier`, adj_list)
}

#' partition_alg
#' 
#' Blah blah blah
#'
#' @param adj_list Adjacency list
#' @export
partition_alg <- function(adj_list, weights, min_w, max_w, n_part, reduce = TRUE) {
    .Call(`_Rzdd_partition_alg`, adj_list, weights, min_w, max_w, n_part, reduce)
}

