# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dd_to_dot <- function(dd) {
    .Call(`_Rzdd_dd_to_dot`, dd)
}

dd_to_sapporo <- function(dd) {
    .Call(`_Rzdd_dd_to_sapporo`, dd)
}

dd_size <- function(dd) {
    .Call(`_Rzdd_dd_size`, dd)
}

dd_cardinality <- function(dd) {
    .Call(`_Rzdd_dd_cardinality`, dd)
}

dd_solutions <- function(dd, use_obi = TRUE) {
    .Call(`_Rzdd_dd_solutions`, dd, use_obi)
}

#' partition_alg
#' 
#' Blah blah blah
#'
#' @param adj_list Adjacency list
#' @export
partition_alg <- function(adj_list, weights, min_w, max_w, n_part, reduce = TRUE) {
    .Call(`_Rzdd_partition_alg`, adj_list, weights, min_w, max_w, n_part, reduce)
}

#' @param adj_list Adjacency list
#' @export
test_graph <- function(adj_list) {
    invisible(.Call(`_Rzdd_test_graph`, adj_list))
}

